### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [uriel-fanelli/ollyster#1]
The repo seems to be lacking a free license. I suggest "AGPLv3 or later", since this is a web-based application.

**Comment by uriel-fanelli** [comment]
I thought GitHub was adding the license when I created it. Very strange.

Anyhow, added it. Thanks for helping.

**Comment by uriel-fanelli** [comment]
LICENSE.md added with GNU Licence V3.

**Comment by uriel-fanelli** [comment]
License added, so closing.
